<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>latestmajor</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>FluffyVoid.EventBus</RootNamespace>
        <AssemblyName>FluffyVoid.EventBus</AssemblyName>
        <PackageId>FluffyVoid.EventBus</PackageId>
        <Title>EventBus</Title>
        <Authors>FluffyVoid</Authors>
        <Description>Thread-safe C# event bus framework that allows for subscribing and publishing events in a decoupled method.</Description>
        <Company>FluffyVoid</Company>
        <Product>FluffyVoid.EventBus</Product>
        <AssemblyVersion>1.0.2</AssemblyVersion>
        <FileVersion>1.0.2</FileVersion>
        <RepositoryUrl>https://github.com/ashiryn/EventBus</RepositoryUrl>
        <Version>1.0.2</Version>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <DocumentationFile>bin/Debug/FluffyVoid.EventBus.xml</DocumentationFile>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DocumentationFile>bin/Release/FluffyVoid.EventBus.xml</DocumentationFile>
    </PropertyGroup>
	<ItemGroup>
        <None Include="bin/$(Configuration)/FluffyVoid.EventBus.xml" Pack="true">
            <PackageCopyToOutput>true</PackageCopyToOutput>
            <PackageFlatten>true</PackageFlatten>
        </None>
	</ItemGroup>
</Project>
