<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latestmajor</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>FluffyVoid.EventBus</RootNamespace>
        <AssemblyName>FluffyVoid.EventBus</AssemblyName>
        <PackageId>FluffyVoid.EventBus</PackageId>
        <Title>EventBus</Title>
        <Authors>FluffyVoid</Authors>
        <Description>Thread-safe C# event bus framework that allows for subscribing and publishing events in a decoupled method.</Description>
        <Company>FluffyVoid</Company>
        <Product>FluffyVoid.EventBus</Product>
        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>
        <RepositoryUrl>https://github.com/ashiryn/EventBus</RepositoryUrl>
    </PropertyGroup>

</Project>
